---
- name: Preparation du serveur
  hosts: all
  remote_user: root
  vars_files: vars.yml

  tasks:
  - name: update system
    command: apt update

  - name: install python
    command: apt install python3
 
  - name: Cr√©er un container
    docker_container:
      name: redis
      image: redis
      volumes:
        - /data 